branches:
    only:
        - master

stages:
    - build
    - name: doc
      if: type = push
    - name: deploy
      if: type = push

matrix:
    include:
        - language: python
          stage: build
          python: 2.7
          install:
              - docker pull $DOCKER_AUX_REPO
              - sudo cp .ci/protoc /bin/protoc
              - sudo chmod +x /bin/protoc
              - pip install --upgrade pytest protobuf lz4
          script:
              - python setup.py build_py
              - pytest
        - language: python
          python: 3.6
          install:
              - docker pull $DOCKER_AUX_REPO
              - sudo cp .ci/protoc /bin/protoc
              - sudo chmod +x /bin/protoc
              - pip install --upgrade pytest pytest-coverage codecov protobuf lz4
          script:
              - python setup.py build_py
              - pytest --cov=proio --cov-report term-missing
          after_success: codecov
        - language: python
          python: nightly
          install:
              - docker pull $DOCKER_AUX_REPO
              - sudo cp .ci/protoc /bin/protoc
              - sudo chmod +x /bin/protoc
              - pip install --upgrade pytest protobuf lz4
          script:
              - python setup.py build_py
              - pytest

        - language: python
          stage: doc
          install:
              - docker pull $DOCKER_AUX_REPO
              - sudo cp .ci/protoc /bin/protoc
              - sudo chmod +x /bin/protoc
              - pip install --upgrade sphinx pkginfo
          script:
              - python setup.py build_py sdist
              - pip install --upgrade .
              - cd docs
              - bash genAndDeploy.sh

        - language: python
          stage: deploy
          install:
              - docker pull $DOCKER_AUX_REPO
              - sudo cp .ci/protoc /bin/protoc
              - sudo chmod +x /bin/protoc
              - pip install --upgrade protobuf lz4
          script:
              - sed -i "s/\(version = '[0-9]*\.[0-9]*\)'/\1.$TRAVIS_BUILD_NUMBER'/" setup.py
              - sed -i "s/'protobuf==[0-9\.*]*'/'$(pip freeze | grep protobuf | sed 's/==/>=/')'/" setup.py
              - python setup.py build_py
          deploy:
              provider: pypi
              user: $PYPI_USERNAME
              password: $PYPI_PASSWORD
              skip_cleanup: true

    allow_failures:
        - python: nightly
    fast_finish: true
    sudo: true
    services:
        - docker
